package Hibernate.src.fr.ifsic.jdbc.film;

// Generated 2 d�c. 2011 08:34:14 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import org.hibernate.Session;

/**
 * Personne generated by hbm2java
 */
public class Personne implements java.io.Serializable {

	private Integer p;
	private String nom;
	private String prenom;
	private String sexe;
	private Acteur acteur;
	private Set<Film> films = new HashSet<Film>(0);
	private Set<Vedette> vedettes = new HashSet<Vedette>(0);

	public Personne() {
	}

	public Personne(String nom) {
		this.nom = nom;
	}

	public Personne(String nom, String prenom, String sexe, Acteur acteur,
			Set<Film> films, Set<Vedette> vedettes) {
		this.nom = nom;
		this.prenom = prenom;
		this.sexe = sexe;
		this.acteur = acteur;
		this.films = films;
		this.vedettes = vedettes;
	}

	public Integer getP() {
		return this.p;
	}

	public void setP(Integer p) {
		this.p = p;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getSexe() {
		return this.sexe;
	}

	public void setSexe(String sexe) {
		this.sexe = sexe;
	}

	public Acteur getActeur() {
		return this.acteur;
	}

	public void setActeur(Acteur acteur) {
		this.acteur = acteur;
	}

	public Set<Film> getFilms() {
		return this.films;
	}

	public void setFilms(Set<Film> films) {
		this.films = films;
	}

	public Set<Vedette> getVedettes() {
		return this.vedettes;
	}

	public void setVedettes(Set<Vedette> vedettes) {
		this.vedettes = vedettes;
	}
	
}
