package Hibernate.src.fr.ifsic.jdbc.film;

// Generated 2 d�c. 2011 08:34:14 by Hibernate Tools 3.4.0.CR1

/**
 * Vedette generated by hbm2java
 */
public class Vedette implements java.io.Serializable {

	private VedetteId id;
	private Film film;
	private Personne personne;
	private String role;

	public Vedette() {
	}

	public Vedette(VedetteId id, Film film, Personne personne) {
		this.id = id;
		this.film = film;
		this.personne = personne;
	}

	public Vedette(VedetteId id, Film film, Personne personne, String role) {
		this.id = id;
		this.film = film;
		this.personne = personne;
		this.role = role;
	}

	public VedetteId getId() {
		return this.id;
	}

	public void setId(VedetteId id) {
		this.id = id;
	}

	public Film getFilm() {
		return this.film;
	}

	public void setFilm(Film film) {
		this.film = film;
	}

	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
