package Hibernate.src.fr.ifsic.jdbc.film;

// Generated 2 d�c. 2011 08:34:14 by Hibernate Tools 3.4.0.CR1

/**
 * VedetteId generated by hbm2java
 */
public class VedetteId implements java.io.Serializable {

	private int f;
	private int p;

	public VedetteId() {
	}

	public VedetteId(int f, int p) {
		this.f = f;
		this.p = p;
	}

	public int getF() {
		return this.f;
	}

	public void setF(int f) {
		this.f = f;
	}

	public int getP() {
		return this.p;
	}

	public void setP(int p) {
		this.p = p;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VedetteId))
			return false;
		VedetteId castOther = (VedetteId) other;

		return (this.getF() == castOther.getF())
				&& (this.getP() == castOther.getP());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getF();
		result = 37 * result + this.getP();
		return result;
	}

}
